### PR TITLE
Doc/readme updates v0

### PR DESCRIPTION
**Pull request by julian-zucker**
@drassaby I finished up the tiny amount of documentation left after our big documentation push on Thursday. Let me know if there's anything I missed!

### CODE REVIEW

**Comment by drassaby** [comment]
@julian-zucker The serializability section looks good. I added some more sections you should look over. Basically about how to use Evvo before we make it a Maven and sbt dependency. I also think @rachlin should review this PR to have another set of fresh eyes on it.

@rachlin does that work for you?

**Comment by drassaby** [comment]
@rachlin, if you see any terminology that's not consistent with the current research, definitely worth bringing up. You're the most up to date with evolutionary computing research

**Comment by julian-zucker** [comment]
@drassaby Looks good to me. Requiring git submodules is not the ideal long-term solution, but it is the best way for end users to use Evvo right now.

**Comment by rachlin** [comment]
My comments on the README:

It's ok for now, but the first thing we show is "Minimizing 1's in a bitstring" and that's just a silly example.  I'm worried we won't be taken seriously.  I would drop it, or replace it with a a mocked up example that people can relate to like TSP or wedding seat planning.   

Maybe start with the section on the Model. That documentation is very good. 

I dig the ascii art but you have to scroll left and right to see the entire image.

**Comment by drassaby** [comment]
> My comments on the README:
> 
> It's ok for now, but the first thing we show is "Minimizing 1's in a bitstring" and that's just a silly example. I'm worried we won't be taken seriously. I would drop it, or replace it with a a mocked up example that people can relate to like TSP or wedding seat planning.
> 
> Maybe start with the section on the Model. That documentation is very good.
> 
> I dig the ascii art but you have to scroll left and right to see the entire image.

@rachlin we wanted it to be the simplest possible example. I think the getting started (#93) should be a much more interesting problem. If we added that in a future PR (before v0), would that fix your concern?

**Comment by julian-zucker** [comment]
@rachlin I based it off [https://github.com/jenetics/jenetics](https://github.com/jenetics/jenetics), their quickstart is also minimizing ones. The point is to show the API, people can (hopefully) understand that it generalizes.

**Comment by julian-zucker** [comment]
@drassaby let me know if this is wrong, but I believe this PR closes #78 and closes #40

**Comment by drassaby** [comment]
@julian-zucker yep, it resolves both. That just leaves #93 left for our v0 milestone

**Comment by drassaby** [comment]
@rachlin, I fixed the issue where users have to scroll sideways in the README. I think it's ready to merge now

**Pull request merged**
