### PR TITLE
Ability to Add Solutions to the Population

### LINKED ISSUE #157: Ability to Set Initial Populations
**Is your feature request related to a problem? Please describe.**
Some optimization problems start with good data that you may want to use as a starting point.

**Describe the solution you'd like**
You should be able to pass in an initial population to an Island.

**Additional context**
This also makes it easier to benchmark performance changes since you can start with the same data each time.

### PR DESCRIPTION
**Pull request by drassaby**
Resolves #157 .

User can now add solutions to the population through the island manager.

If a user wants to add an initial population, they can just do this:
```scala
val mgr = new IslandManager[Sol](..)
mgr.addSolutions(sequenceOfSolutionsToAdd)
```

### CODE REVIEW

**Comment by julian-zucker** [comment]
This looks good generally. Should `addSolutions` be on the manager? To me, it would make more sense to be able to add it to the builder (which would also mean you wouldn't need a creator), and then have islands accept solutions in their constructor. As it is, we will have some duplication between `addSolutions` and `immigrate`.

**Comment by drassaby** [comment]
> This looks good generally. Should `addSolutions` be on the manager? To me, it would make more sense to be able to add it to the builder (which would also mean you wouldn't need a creator), and then have islands accept solutions in their constructor. As it is, we will have some duplication between `addSolutions` and `immigrate`.

@julian-zucker that was my first thought too for how to implement it. But I moved away from that since some optimization problems may be extremely long running and users should be able to add solutions at any point along the way without creating and distributing new islands from scratch. This implementation allows us to do that.

It also distributes the given solutions to the islands, which means that each island starts out pretty different from all the others, potentially giving the total population greater diversity over time. Good solutions will still be shared with immigration anyway

**Comment by julian-zucker** [comment]
Alright, I buy the argument about wanting to add solutions to problems while they're running. I still think it makes more sense to add the solutions to the builder, and not need to add a creator if you have added a starting population. Does that seem reasonable to you?

**Comment by drassaby** [comment]
> Alright, I buy the argument about wanting to add solutions to problems while they're running. I still think it makes more sense to add the solutions to the builder, and not need to add a creator if you have added a starting population. Does that seem reasonable to you? If so, do that and I'll merge.

You are 100% right that we need to change the builder. Good catch, didn't think of that! The added solutions are distributed among the islands as opposed to adding each solution to every island (to try to help islands evolve separately), but an island builder (conceptually) should have all the info needed to create an island. I think it makes more sense to just not require creators as part of the builder, since users can add solutions at any point along the process anyway. I'm also not too concerned about users forgetting to input a creator or starting solutions, since that would be an easy bug to spot/resolve. What do you think about that approach @julian-zucker?

**Comment by julian-zucker** [comment]
I understand the dilemma about starting each island with the same solutions. It still seems unfortunate to have a two steps required to build an island. That seems counterintuitive to new users. Maybe we can add all the solutions to the island builder, and then pass in the island's index/max index to the build method, and have them round-robin choose solutions at build-time? Or have a `buildNIslands` method that will round-robin choose. 

I'm okay with either way at this point, do what you feel is right.

**Comment by drassaby** [comment]
> I understand the dilemma about starting each island with the same solutions. It still seems unfortunate to have a two steps required to build an island. That seems counterintuitive to new users. Maybe we can add all the solutions to the island builder, and then pass in the island's index/max index to the build method, and have them round-robin choose solutions at build-time? Or have a `buildNIslands` method that will round-robin choose.
> 
> I'm okay with either way at this point, do what you feel is right.

I think for now I'm happiest with just not requiring the creators in the island builder. But I can see how it would seem counterintuitive, since the problem is not set up entirely in one step. Would it help if we allowed adding an initial population through the island manager constructor? I don't see the same problems with that as I do with adding them to the island builder. But do you think it would be simpler since the problem can be set up in one step or more confusing since there would be two ways to do the same operation?

**Comment by julian-zucker** [comment]
Making creators optional is fine. Perhaps log a warning when running without creators? I think we should avoid having the island manager constructor take anything more than it has to.

**Comment by drassaby** [comment]
> Making creators optional is fine. Perhaps log a warning when running without creators? I think we should avoid having the island manager constructor take anything more than it has to.

Done! :)

**Pull request merged**
